name: ci

on:
  push:
    tags:
      - '*'
  pull_request:
    tags:
      - '*'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set env
        run: cat environment.sh >> $GITHUB_ENV

      - name: Set perl modules env
        run: echo "CPAN_MODULES=$(grep -E '^[A-Z].+' cpan_modules.txt | tr '\n' ' ')" >> $GITHUB_ENV

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ryanlauterbach/docker-perl-catalyst
          tags: |
            type=ref,event=tag
            # set latest tag for default branch
            type=raw,value=latest,enable={{is_default_branch}}
            type=schedule,pattern={{date 'YYYYMMDD.HH:mm:ss'}}
            
      - name: Login to DockerHub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          build-args: |
            PERL_DOCKER_TAG=${{ env.PERL_DOCKER_TAG }}
            CPAN_MODULES=${{ env.CPAN_MODULES }}
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.PERL_DOCKER_TAG }}
          labels: ${{ steps.meta.outputs.labels }}
